
STRING_SEND = "Send"
STRING_POS = "Pos"
STRING_STOP = "STOP"
STRING_MARKET = "Market"
STRING_TRAILING = "Trailing"
STRING_LIMIT = "Limit"
STRING_SMRTL = "SMRTL"
STRING_ROUND = "ROUND"
STRING_ROUND2 = "Round2"
STRING_DAY_PLUS = "Day+"
INT_ZERO = 0
